name: Pull Request Assigner

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assigner:
    runs-on: ubuntu-latest
    name: Assign
    steps:
      - name: Assign
        uses: examedi/pull-request-assigner@master
        with:
          configuration-path: ".github/assign_reviewers.yml"
